### ISSUE TITLE
Removes only 1 product instead of 250

### ISSUE THREAD

**Issue by nickweisser** [greguly/WooCommerce-Remove-All-Products#2]
This looks like a bug, not sure why. My first guess would be that we're using WPML :-)

It says it's removing 250, but then only removes 1. Bummer.

![screen shot 2015-06-30 at 13 26 14](https://cloud.githubusercontent.com/assets/58966/8429837/b95c02c0-1f2b-11e5-98ce-c04bf8d420de.png)
![screen shot 2015-06-30 at 13 25 53](https://cloud.githubusercontent.com/assets/58966/8429836/b959282a-1f2b-11e5-994b-aae139275ef3.png)

**Comment by greguly** [comment]
Hi Nick,

Apologies fo the late reply. 

Thanks for the report, but that is not a bug. The server was about to timeout the plugin hence it stopped itself.

Howerver you raised a good point, the wording of 'Removing 250 products' shall be changed to 'Trying to remove 250 products'.

WPML makes copies of the products, so depending on the number of languages it could have 2 or more extra product removals to be done at each step.

Looking at your log, it shows that the timeout is happening after just 1 second, so I guess you might want to check your server configurations.

Here there are some tips: https://wordpress.org/support/topic/plugin-cp-import-tips-and-tricks-avoiding-script-time-out

Cheers,
Gabriel
