### ISSUE TITLE
not deleting after update to wordpress 4.7

### ISSUE THREAD

**Issue by jonpastore** [greguly/WooCommerce-Remove-All-Products#6]
It says stopped after imminent time out detected. only deletes 25-29 products at a time. Please help.

**Comment by greguly** [comment]
This is not a support forum, try WordPress.org 

[https://wordpress.org/support/plugin/woocommerce-remove-all-products/](https://wordpress.org/support/plugin/woocommerce-remove-all-products/)

**Comment by jonpastore** [comment]
4 years....lol. Thank god I didn't rely on this! Maybe I'll retire before
the next response! ha.
